#version de docker compose
version: '3.8'
# Services que le veut lancer
services:

  nginx:
    image: nginx:1.18
    container_name: nginxPV
    ports:
      - 80:80
    #répertoires partages :: repertoire hote : repertoire container 
    volumes:
      - ./src:/var/www/
      - ./docker_phys/nginx/conf.d/default.d:/etc/nginx/conf.d/default.conf
    #configuration du repertoire de travail  
    working_dir: /var/www/

  # PHP Service
  php:
    image: test_php
    container_name: phpPV
    working_dir: /var/www/
    volumes:
      - ./src:/var/www/

  # MySQL Service
  mysql:
    image: mysql/mysql-server:8.0
    container_name: mysqlPV
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'      
    ports:
            - 3306:3306
    
  phpmyadmin:
    image:  phpmyadmin/phpmyadmin:5
    container_name: phpmyadminPV
    ports : 
        - 8080:80
    environment:
      PMA_HOST: mysql      
            
# Volumes
volumes:
   mysqldata:
    driver: local